# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Platypus Blue
email: platypusblue@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  This is the internet home for the Platypus Blue Collective.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://platypus.blue" # the base hostname & protocol for your site
twitter_username: platypusblue
github_username:  platypusblue

# Build settings
markdown: kramdown
